#!/usr/bin/env bash

name=$(basename "$(pwd)")
dockerName=$(echo "$name" | sed 's/ /-/g' | sed 's/\([a-z0-9]\)\([A-Z]\)/\1-\2/g' | tr '[:upper:]' '[:lower:]')

DOCKER_COMPOSE_COMMAND="php artisan $@" docker-compose -f docker-compose.yml -f docker-compose.artisan.yml up --exit-code-from laravel
