version: "3"
services:
  laravel:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/app
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_DATABASE: laravel
